=== jnnycn007/skia-buildbot/perf/go/config/validate/instanceConfigSchema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://go.skia.org/infra/perf/go/config/instance-config",
  "$ref": "#/$defs/InstanceConfig",
  "$defs": {
    "AnomalyConfig": {
      "properties": {
        "settling_time": {
          "$ref": "#/$defs/DurationAsString"
        },
        "use_anomaly_localization": {
          "type": "boolean"
        },
        "process_alert_configs_worker_count": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "ApplyDefault": {
      "properties": {
        "param": {
          "type": "string"
        },
        "values": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "select_only_first": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "param",
        "values",
        "select_only_first"
      ]
    },
    "AuthConfig": {
      "properties": {
        "header_name": {
          "type": "string"
        },
        "email_regex": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "header_name"
      ]
    },
    "CacheConfig": {
      "properties": {
        "memcached_servers": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "namespace": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "memcached_servers",
        "namespace"
      ]
    },
    "ConditionalDefaultRule": {
      "properties": {
        "trigger": {
          "$ref": "#/$defs/TriggerCondition"
        },
        "apply": {
          "items": {
            "$ref": "#/$defs/ApplyDefault"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "trigger",
        "apply"
      ]
    },
    "DataPointConfig": {
      "properties": {
        "keys_for_commit_range": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "keys_for_useful_links": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "skip_commit_detail_display": {
          "type": "boolean"
        },
        "enable_point_links": {
          "type": "boolean"
        },
        "show_json_file_display": {
          "type": "boolean"
        },
        "always_show_commit_info": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "DataStoreConfig": {
      "properties": {
        "datastore_type": {
          "type": "string"
        },
        "connection_string": {
          "type": "string"
        },
        "tile_size": {
          "type": "integer"
        },
        "cache": {
          "$ref": "#/$defs/CacheConfig"
        },
        "enable_follower_reads": {
          "type": "boolean"
        },
        "min_db_connections": {
          "type": "integer"
        },
        "traceparams_param_indexes": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "datastore_type",
        "connection_string",
        "tile_size"
      ]
    },
    "DurationAsString": {
      "type": "string",
      "title": "Duration",
      "description": "A golang time.Duration serialized as a string."
    },
    "Experiments": {
      "properties": {
        "remove_default_stat_value": {
          "type": "boolean"
        },
        "enable_skia_bridge_aggregation": {
          "type": "boolean"
        },
        "preflight_subqueries_for_existing_keys": {
          "type": "boolean"
        },
        "progress_use_redis_cache": {
          "type": "boolean"
        },
        "regressions_trace_id_field": {
          "type": "boolean"
        },
        "df_iter_trace_slicer": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "ExtraLinks": {
      "properties": {
        "name": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "links": {
          "items": {
            "$ref": "#/$defs/FavoritesSectionLinkConfig"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "title",
        "links"
      ]
    },
    "Favorites": {
      "properties": {
        "sections": {
          "items": {
            "$ref": "#/$defs/FavoritesSectionConfig"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "sections"
      ]
    },
    "FavoritesSectionConfig": {
      "properties": {
        "name": {
          "type": "string"
        },
        "links": {
          "items": {
            "$ref": "#/$defs/FavoritesSectionLinkConfig"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name",
        "links"
      ]
    },
    "FavoritesSectionLinkConfig": {
      "properties": {
        "id": {
          "type": "string"
        },
        "text": {
          "type": "string"
        },
        "href": {
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "text",
        "href",
        "description"
      ]
    },
    "GitRepoConfig": {
      "properties": {
        "git_auth_type": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "start_commit": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "dir": {
          "type": "string"
        },
        "file_change_marker": {
          "type": "string"
        },
        "debounce_commit_url": {
          "type": "boolean"
        },
        "commit_url": {
          "type": "string"
        },
        "commit_number_regex": {
          "type": "string"
        },
        "branch": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "provider",
        "url",
        "dir"
      ]
    },
    "IngestionConfig": {
      "properties": {
        "source_config": {
          "$ref": "#/$defs/SourceConfig"
        },
        "branches": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "file_ingestion_pubsub_topic_name": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "source_config",
        "branches",
        "file_ingestion_pubsub_topic_name"
      ]
    },
    "InstanceConfig": {
      "properties": {
        "URL": {
          "type": "string"
        },
        "instance_name": {
          "type": "string"
        },
        "header_image_url": {
          "type": "string"
        },
        "landing_page_rel_path": {
          "type": "string"
        },
        "backend_host_url": {
          "type": "string"
        },
        "allowed_hosts": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "contact": {
          "type": "string"
        },
        "invalid_param_char_regex": {
          "type": "string"
        },
        "fetch_chrome_perf_anomalies": {
          "type": "boolean"
        },
        "fetch_anomalies_from_sql": {
          "type": "boolean"
        },
        "feedback_url": {
          "type": "string"
        },
        "chat_url": {
          "type": "string"
        },
        "help_url_override": {
          "type": "string"
        },
        "bug_host_url": {
          "type": "string"
        },
        "favorites": {
          "$ref": "#/$defs/Favorites"
        },
        "extra_links": {
          "$ref": "#/$defs/ExtraLinks"
        },
        "filter_parent_traces": {
          "type": "boolean"
        },
        "trace_sample_proportion": {
          "type": "number"
        },
        "trace_format": {
          "type": "string"
        },
        "need_alert_action": {
          "type": "boolean"
        },
        "use_regression2_schema": {
          "type": "boolean"
        },
        "auth_config": {
          "$ref": "#/$defs/AuthConfig"
        },
        "data_store_config": {
          "$ref": "#/$defs/DataStoreConfig"
        },
        "ingestion_config": {
          "$ref": "#/$defs/IngestionConfig"
        },
        "git_repo_config": {
          "$ref": "#/$defs/GitRepoConfig"
        },
        "notify_config": {
          "$ref": "#/$defs/NotifyConfig"
        },
        "issue_tracker_config": {
          "$ref": "#/$defs/IssueTrackerConfig"
        },
        "anomaly_config": {
          "$ref": "#/$defs/AnomalyConfig"
        },
        "query_config": {
          "$ref": "#/$defs/QueryConfig"
        },
        "temporal_config": {
          "$ref": "#/$defs/TemporalConfig"
        },
        "data_point_config": {
          "$ref": "#/$defs/DataPointConfig"
        },
        "enable_sheriff_config": {
          "type": "boolean"
        },
        "sheriff_configs_to_notify": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "ga_measurement_id": {
          "type": "string"
        },
        "new_alerts_page": {
          "type": "boolean"
        },
        "optimize_sqltracestore": {
          "type": "boolean"
        },
        "experiments": {
          "$ref": "#/$defs/Experiments"
        },
        "show_triage_link": {
          "type": "boolean"
        },
        "show_bisect_btn": {
          "type": "boolean"
        },
        "show_hash_ranges_in_tooltip": {
          "type": "boolean"
        },
        "allow_multiple_regressions_per_alert_id": {
          "type": "boolean"
        },
        "enable_v2_ui": {
          "type": "boolean"
        },
        "default_to_manual_plot_mode": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "URL",
        "contact",
        "data_store_config",
        "ingestion_config",
        "git_repo_config",
        "notify_config"
      ]
    },
    "IssueTrackerConfig": {
      "properties": {
        "notification_type": {
          "type": "string"
        },
        "issue_tracker_api_key_secret_project": {
          "type": "string"
        },
        "issue_tracker_api_key_secret_name": {
          "type": "string"
        },
        "culprit_subject": {
          "type": "string"
        },
        "culprit_body": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "anomaly_report_subject": {
          "type": "string"
        },
        "anomaly_report_body": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "notification_type"
      ]
    },
    "NotifyConfig": {
      "properties": {
        "notifications": {
          "type": "string"
        },
        "issue_tracker_api_key_secret_project": {
          "type": "string"
        },
        "issue_tracker_api_key_secret_name": {
          "type": "string"
        },
        "subject": {
          "type": "string"
        },
        "body": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "missing_subject": {
          "type": "string"
        },
        "missing_body": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "data_provider": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "notifications"
      ]
    },
    "QueryCacheConfig": {
      "properties": {
        "type": {
          "type": "string"
        },
        "level1_cache_key": {
          "type": "string"
        },
        "level1_cache_values": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "level2_cache_key": {
          "type": "string"
        },
        "level2_cache_values": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "enabled": {
          "type": "boolean"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "type"
      ]
    },
    "QueryConfig": {
      "properties": {
        "include_params": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "default_param_selections": {
          "patternProperties": {
            ".*": {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        },
        "default_url_values": {
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "cache_config": {
          "$ref": "#/$defs/QueryCacheConfig"
        },
        "redis_config": {
          "$ref": "#/$defs/RedisConfig"
        },
        "query_commit_chunk_size": {
          "type": "integer"
        },
        "max_empty_tiles": {
          "type": "integer"
        },
        "default_range": {
          "type": "integer"
        },
        "default_xaxis_domain": {
          "type": "string"
        },
        "conditional_defaults": {
          "items": {
            "$ref": "#/$defs/ConditionalDefaultRule"
          },
          "type": "array"
        },
        "default_trigger_priority": {
          "patternProperties": {
            ".*": {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "RedisConfig": {
      "properties": {
        "project": {
          "type": "string"
        },
        "zone": {
          "type": "string"
        },
        "instance": {
          "type": "string"
        },
        "cache_expiration_minutes": {
          "type": "integer"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "SourceConfig": {
      "properties": {
        "source_type": {
          "type": "string"
        },
        "project": {
          "type": "string"
        },
        "topic": {
          "type": "string"
        },
        "subscription": {
          "type": "string"
        },
        "dl_topic": {
          "type": "string"
        },
        "dl_subscription": {
          "type": "string"
        },
        "sources": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "reject_if_name_matches": {
          "type": "string"
        },
        "accept_if_name_matches": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "source_type",
        "project",
        "topic",
        "subscription",
        "sources"
      ]
    },
    "TemporalConfig": {
      "properties": {
        "host_port": {
          "type": "string"
        },
        "namespace": {
          "type": "string"
        },
        "grouping_task_queue": {
          "type": "string"
        },
        "pinpoint_task_queue": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "type": "object"
    },
    "TriggerCondition": {
      "properties": {
        "param": {
          "type": "string"
        },
        "values": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "param",
        "values"
      ]
    }
  }
}

=== jnnycn007/skia-buildbot/perf/configs/spanner/chrome-internal-autopush.json
{
    "URL": "https://chrome-perf-autopush.corp.goog",
    "landing_page_rel_path": "/m/",
    "header_image_url": "/dist/images/chrome-logo.svg",
    "ga_measurement_id": "G-PFC9BX9411",
    "allowed_hosts": [],
    "backend_host_url": "perf-be-chrome-non-public.perf.svc.cluster.local:8000",
    "contact": "browser-perf-engprod@google.com",
    "instance_name": "chrome-internal (Autopush)",
    "trace_sample_proportion": 0.1,
    "invalid_param_char_regex": "([^a-zA-Z0-9!~@#$%^&*()+ :\\._\\-])",
    "fetch_chrome_perf_anomalies": true,
    "use_regression2_schema": true,
    "bug_host_url": "https://issues.chromium.org",
    "feedback_url": "http://go/berf-skia-feedback",
    "chat_url": "http://go/berf-skia-chat",
    "filter_parent_traces": true,
    "notify_config": {
        "notifications": "anomalygroup"
    },
    "issue_tracker_config": {
        "notification_type": "issuetracker",
        "issue_tracker_api_key_secret_project": "skia-infra-public",
        "issue_tracker_api_key_secret_name": "perf-issue-tracker-apikey"
    },
    "auth_config": {
        "header_name": "X-WEBAUTH-USER"
    },
    "data_store_config": {
        "datastore_type": "spanner",
        "connection_string": "postgresql://root@localhost:5432/chrome_int_autopush?sslmode=disable",
        "tile_size": 8192,
        "enable_follower_reads": true,
        "min_db_connections": 5
    },
    "experiments": {
        "enable_skia_bridge_aggregation": true,
        "df_iter_trace_slicer": true,
        "regressions_trace_id_field": true
    },
    "ingestion_config": {
        "source_config": {
            "source_type": "gcs",
            "project": "skia-public",
            "topic": "perf-ingestion-chrome-internal-autopush",
            "subscription": "perf-ingestion-chrome-internal-autopush",
            "sources": [
                "gs://chrome-perf-non-public/ingest"
            ]
        },
        "branches": [],
        "file_ingestion_pubsub_topic_name": "perf-cluster-chrome-non-public-autopush"
    },
    "git_repo_config": {
        "provider": "gitiles",
        "url": "https://chromium.googlesource.com/chromium/src",
        "dir": "/tmp/checkout",
        "debounce_commit_url": false,
        "file_change_marker": "",
        "start_commit": "b7fa4587f55a066e97f79b4c97ed785dc217064b",
        "commit_number_regex": "Cr-Commit-Position: refs/heads/(main|master)@\\{#(.*)\\}"
    },
    "extra_links": {
        "name": "CBB",
        "title": "Comparative Browser Benchmarking (CBB)",
        "links": [
            {
                "text": "Mac (go/cbb-mac)",
                "href": "https://chrome-perf.corp.goog/m?begin=1752000000&end=1780000000&numCommits=50&shortcut=dd0dd339ebb06e5f01e64de82f3977d1&splitByKeys=benchmark&totalGraphs=4",
                "description": "CBB results on Mac"
            },
            {
                "text": "Windows x64 (go/cbb-win)",
                "href": "https://chrome-perf.corp.goog/m?begin=1752000000&end=1780000000&numCommits=50&shortcut=8e3d2605de2b3e17fa257ea47275ee0a&splitByKeys=benchmark&totalGraphs=4",
                "description": "CBB results on Windows (Intel CPU)"
            },
            {
                "text": "Windows ARM64 (go/cbb-win-arm)",
                "href": "https://chrome-perf.corp.goog/m?begin=1752000000&end=1780000000&numCommits=50&shortcut=1adc4014bca70f8245c3250c46ff2abc&splitByKeys=benchmark&totalGraphs=4",
                "description": "CBB results on Windows (ARM64 CPU)"
            },
            {
                "text": "Pixel Tablet (go/cbb-tangor)",
                "href": "https://chrome-perf.corp.goog/m?begin=1752000000&end=1780000000&numCommits=35&shortcut=134f1b581613f1f4bbe63b66719ff588&splitByKeys=benchmark&totalGraphs=5",
                "description": "CBB results on Pixel Tablet (Tangor)"
            },
            {
                "text": "Speedometer3 (go/cbb-sp3)",
                "href": "https://chrome-perf.corp.goog/m?begin=1752000000&end=1780000000&numCommits=50&shortcut=7bd8bba5abb81582cffb5cb8578011b2&splitByKeys=bot&totalGraphs=4",
                "description": "CBB Speedometer3 results"
            },
            {
                "text": "JetStream2 (go/cbb-js2)",
                "href": "https://chrome-perf.corp.goog/m?begin=1752000000&end=1780000000&numCommits=50&shortcut=c68938c0463f91bfc8b1e9a8aca18499&splitByKeys=bot&totalGraphs=4",
                "description": "CBB JetStream2 results"
            },
            {
                "text": "JetStream3 (go/cbb-js3)",
                "href": "https://chrome-perf.corp.goog/m?begin=1752000000&end=1780000000&numCommits=50&shortcut=996f59da14c437bbef118c9514ea4724&splitByKeys=bot&totalGraphs=4",
                "description": "CBB JetStream3 results"
            },
            {
                "text": "MotionMark (go/cbb-mm)",
                "href": "https://chrome-perf.corp.goog/m?begin=1752000000&end=1780000000&numCommits=50&shortcut=598f56484c8e1602be056849b115e0b8&splitByKeys=bot&totalGraphs=4",
                "description": "CBB MotionMark results"
            },
            {
                "text": "Loadline 2 (go/cbb-ll)",
                "href": "https://chrome-perf.corp.goog/m/?begin=1752000000&end=1780000000&numCommits=20&shortcut=3d5e9ef84f6673ca273c3cabb4297113&totalGraphs=1",
                "description": "CBB Loadline 2 results (Android only)"
            },
            {
                "text": "Overall results (go/cbb-all)",
                "href": "https://chrome-perf.corp.goog/m?begin=1752000000&end=1780000000&numCommits=50&shortcut=81ad17a19b621a127443d95ffe7e28b3&splitByKeys=benchmark&totalGraphs=5",
                "description": "CBB results for all benchmarks and platforms"
            }
        ]
    },
    "query_config": {
        "include_params": [
            "benchmark",
            "bot",
            "test",
            "subtest_1",
            "subtest_2",
            "subtest_3"
        ],
        "default_param_selections": {
            "stat": ["value"]
        },
        "default_url_values": {
            "plotSummary": "true",
            "useTestPicker": "true",
            "showZero": "false",
            "enable_chart_tooltip": "true",
            "use_titles": "true",
            "show_google_plot": "true"
        },
        "default_range": 604800,
        "cache_config": {
            "type": "redis",
            "level1_cache_key": "benchmark",
            "level2_cache_key": "bot",
            "enabled": true
        },
        "redis_config": {
            "project": "skia-infra-corp",
            "zone": "us-central1",
            "instance": "chrome-internal",
            "cache_expiration_minutes": 300
        }
    },
    "data_point_config": {
        "keys_for_commit_range": ["V8", "WebRTC", "V8 Git Hash", "WebRTC Git Hash"],
        "keys_for_useful_links": [
            "Build Page", "Tracing uri", "Browser Version", "Workflow", "Swarming Tasks"],
        "skip_commit_detail_display": true,
        "show_json_file_display": false
    },
    "temporal_config": {
        "host_port": "temporal.temporal:7233",
        "namespace": "perf-internal",
        "grouping_task_queue": "perf.perf-chrome-internal.grouping",
        "pinpoint_task_queue": "perf.perf-chrome-public.bisect"
    },
    "enable_sheriff_config": true,
    "help_url_override": "http://go/chrome-perf-user-doc",
    "trace_format": "chrome",
    "need_alert_action": true,
    "optimize_sqltracestore": true,
    "new_alerts_page": true,
    "show_triage_link": false,
    "show_bisect_btn": true,
    "show_hash_ranges_in_tooltip": false,
    "allow_multiple_regressions_per_alert_id": true
}

=== jnnycn007/skia-buildbot/perf/configs/spanner/fuchsia-internal-autopush.json
{
    "URL": "https://fuchsia-perf-autopush.corp.goog",
    "header_image_url": "/dist/images/fuchsia.svg",
    "ga_measurement_id": "G-8CM4NHWZ72",
    "landing_page_rel_path": "/m/",
    "allowed_hosts": [],
    "contact": "browser-perf-engprod@google.com",
    "chat_url": "http://go/berf-skia-chat",
    "bug_host_url": "https://issues.chromium.org",
    "feedback_url": "http://go/berf-skia-feedback",
    "trace_sample_proportion": 0.01,
    "invalid_param_char_regex": "([^a-zA-Z0-9!~@#$%^&*()+ :\\._\\-])",
    "fetch_chrome_perf_anomalies": true,
    "fetch_anomalies_from_sql": true,
    "instance_name": "fuchsia-internal (Autopush)",
    "notify_config": {
      "notifications": "html_email"
    },
    "auth_config": {
      "header_name": "X-WEBAUTH-USER"
    },
    "data_store_config": {
      "datastore_type": "spanner",
      "connection_string": "postgresql://root@localhost:5432/fuchsia_int_autopush?sslmode=disable",
      "tile_size": 256
    },
    "experiments": {
      "regressions_trace_id_field": true
    },
    "ingestion_config": {
      "source_config": {
        "source_type": "gcs",
        "project": "skia-public",
        "topic": "perf-ingestion-fuchsia-internal-autopush",
        "subscription": "perf-ingestion-fuchsia-internal-autopush-prod",
        "sources": [
          "gs://fuchsia-perf-non-public/ingest"
        ]
      },
      "branches": [],
      "file_ingestion_pubsub_topic_name": ""
    },
    "issue_tracker_config": {
      "notification_type": "issuetracker",
      "issue_tracker_api_key_secret_project": "skia-infra-public",
      "issue_tracker_api_key_secret_name": "perf-issue-tracker-apikey"
    },
    "git_repo_config": {
      "provider": "gitiles",
      "url": "https://turquoise-internal.googlesource.com/integration/",
      "dir": "/tmp/checkout",
      "debounce_commit_url": false,
      "file_change_marker": "",
        "start_commit": "a6d8ddf98b7419331049209ba89e3ac06455a016"
    },
    "query_config": {
      "include_params": [
        "benchmark",
        "bot",
        "test",
        "subtest_1",
        "subtest_2",
        "subtest_3"
      ],
      "default_param_selections": {
	      "stat": ["value"]
      },
      "default_url_values": {
        "plotSummary": "true",
        "useTestPicker": "true",
        "showZero": "false",
        "enable_chart_tooltip": "true",
        "use_titles": "true",
        "show_google_plot": "true"
      }
    },
    "data_point_config": {
      "keys_for_useful_links": ["Build Log"],
      "skip_commit_detail_display": true,
      "show_json_file_display": true
    },
    "optimize_sqltracestore": true,
    "show_triage_link": true,
    "new_alerts_page": true,
    "show_bisect_btn": true,
    "use_regression2_schema": true,
    "trace_format": "chrome",
    "default_to_manual_plot_mode": true
  }
